baseURL       = "https://prismatic-caramel-d4d449.netlify.app/"
languageCode  = "en-us"
title         = "Let it go, let if flow"
theme         = "roxo"
summarylength = 25

[taxonomies]
  category = 'categories'
  tag = 'tags'
  

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "FREE resources"
    url     = "tags/resources/"
    weight  = 2    
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.webp"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Let go of whatever no longer serves you. Find resources or get a coach. Let it go and let it flow."
  author = "Anay"
  og_image = "images/blog/blog-details-image.webp"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/let-it-go.webp"
    heading               = "Let it go, let it flow"
    tagline               = "RELEASE WHAT NO LONGER SERVES YOU"
    primary_button        = "Get FREE resources"
    primary_button_url    = "tags/resources/"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.resources]
    enable    = true
    title     = "FREE resources"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.webp"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Get in touch"
    primary_button_url  = "contact"
    secondary_button    = "Read more"
    secondary_button_url = "tags/resources/"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "713 Elmwood St.<br>Prior Lake, MN 55372"
      email   = "Anay@letitgo-letitflow.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Resources"
          url  = "tags/resources/"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Pinterest"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help you:"
        description = "let go of bad relationships and<br>beliefs that no longer serve you.<br>We help you find your true self and live it."